"""
Semantic memory: distilled, generalized knowledge derived from many episodes
(e.g. "short emails perform better for category X"). These are NOT hardcoded —
they are generated by the learning engine from accumulated pattern/preference
scores and re-derived whenever asked, so they always reflect current data.
"""
from app.database.repository import PatternRepository, PreferenceRepository


class SemanticMemory:
    def derive_statements(self, min_samples=3):
        """
        Turn learned_patterns + learned_preferences rows into human-readable
        sentences. This is intentionally template-based rather than an LLM call —
        the *content* (which pattern, which score) is what was learned; the
        sentence is just a rendering of it.
        """
        statements = []

        strategy_patterns = PatternRepository.all_for_prefix("strategy:")
        for p in strategy_patterns:
            if p["sample_count"] < min_samples:
                continue
            name = p["pattern_key"].split(":", 1)[1]
            statements.append(
                f"Strategy '{name}' has a learned score of {p['score']:.2f} "
                f"from {p['sample_count']} samples "
                f"({p['positive_feedback']} positive, {p['negative_feedback']} negative, "
                f"{p['reply_count']} replies)."
            )

        component_patterns = PatternRepository.all_for_prefix("component:")
        for p in component_patterns:
            if p["sample_count"] < min_samples:
                continue
            statements.append(
                f"Pattern '{p['pattern_key'].split(':', 1)[1]}' scores {p['score']:.2f} "
                f"after {p['sample_count']} uses."
            )

        for pref in PreferenceRepository.all():
            if pref["evidence_count"] < min_samples or pref["confidence"] < 0.3:
                continue
            statements.append(
                f"{pref['description']} (confidence {pref['confidence']:.2f}, "
                f"from {pref['evidence_count']} observations)."
            )

        return statements
